### ISSUE TITLE
conversion from i2b2 to OMOP for use in OHDSI visualization tools?

### ISSUE THREAD

**Issue by dckc** [chop-dbhi/data-models#108]
Suppose I have the i2b2 demodata and I want to look at it via the OHDSI visualization tools, which are based on OMOP. Do your tools fill the gap yet? If not, is that a feature you'd like to see in this project, or is it out of scope?

If this is already supported, I suppose you could consider this a documentation suggestion; I haven't spent a lot of time looking, but I get the impression this isn't yet a supported feature.

cc @njgraham @russwaitman
context: [PCORnet data quality](https://github.com/PCORnet/DataCommittee/wiki/Data-Quality)

**Comment by aaron0browne** [comment]
The scope of this repository is simply to provide a single-source-of-truth for data models, so I would say it's definitely out of that scope.

We have rolled around the idea of "relationships" between fields in disparate models as a way of defining transformation logic, if not actual transformation code, but no one has taken that idea very far. I think it would be difficult because complex transformation logic is often based on features of the data that are more granular than the schema represented here. For example, an i2b2 to OMOP transformation built for one i2b2 dataset may be completely incompatible with another dataset if the two datasets have different ontologies.

**Comment by aaron0browne** [comment]
@dckc if you are going to be at AMIA in San Francisco this year I would be happy to talk about our data models ideas in general. I'm presenting a poster title "Data Model Interoperability via Standard Representation", appropriately enough.

**Comment by dckc** [comment]
@aaron0browne I don't plan to be at AMIA. I'll look for other opportunities to chat.

**Comment by vojtechhuser** [comment]
I have the same problem. i2b2 -> OMOP
