### ISSUE TITLE
OHDSI added box_size to the drug_strength table

### ISSUE THREAD

**Issue by burrowse** [chop-dbhi/data-models#151]
While building the v2.4 vocab snapshot it was discovered that OHDSI created a new column in the drug_strength table...this will need to be updated in our DDL generation scripts.

**Comment by aaron0browne** [comment]
@eceowl this would be a good chance to show you how the data models services work. Let's connect on it next week.

**Comment by burrowse** [comment]
@aaron0browne @eceowl Any updates on this fix?

**Comment by murphyke** [comment]
@eceowl, currently there is no PEDSnet 2.4 data model definition at https://github.com/chop-dbhi/data-models, so that will have to be created according to @burrowse's [latest documentation](https://github.com/PEDSnet/Data_Models/tree/master/PEDSnet/docs) about the 2.4 data model. It appears that the one OMOP change that will need to be integrated is the addition of `box_size` to `drug_strength`. 

Presumably PEDSnet 2.4 will be based on the latest OMOP data model, so when PEDSNet 2.4 is added to the data-models repo, OMOP 5.0.1 or 5.0.2 should also be added, perhaps as a copy of 5.0 with changes.  Looking at https://github.com/OHDSI/CommonDataModel, 5.0.1 was released in May with changes to the cost-related tables, but in September the `box_size` change was made. I just asked in that repo if the current tip should be enshrined as 5.0.2.

Although not crucial, I think we should make better use of the `description` column in the `models.csv` file in the chop-dbhi data-models repo. This could document that  PEDSNet CDM version X is derived from OMP CDM version Y.

Once the new data models are added to the repo, https://data-models-service.research.chop.edu and https://data-models-sqlalchemy.research.chop.edu should ideally start picking them up. There is a lag of an hour for the former. I think that the latter (used to obtain the DDL for the data models) might need kicking to get it to see data model changes, and we probably need AB's help for that. However, you can always install https://github.com/chop-dbhi/data-models-sqlalchemy locally and use it (via python, docker, or even as a local web service) to generate the DDL.

**Comment by burrowse** [comment]
@murphyke @eceowl @aaron0browne Please ignore my previous question. We are still finalizing one more table for v2.4, will be adding new csv files once that is completed.

**Comment by burrowse** [comment]
Addressed in https://github.com/chop-dbhi/data-models/pull/152
