### ISSUE TITLE
Implement command to produce JSON output for DDL generation

### ISSUE THREAD

**Issue by bruth** [chop-dbhi/data-models#18]
A working intermediate structure is defined [here](https://github.com/PEDSnet/pedsnetcdms/blob/master/pedsnetcdms/pedsnetcdm/models.json).

Depends on #17

**Comment by murphyke** [comment]
Regarding this, I just posted an example of a possible JSON format to PEDSnet/pedsnetcdms#9:

Some comments about that sample:

* I assumed the possibility of multi-column unique constraints and multi-column indexes, should those be in the offing.
* Right now fks are duped in references.csv and `definitions` -- is that intentional, or a refactoring-in-progress?
* Foreign key constraints are treated specially with their own top-level references.csv, but somehow I expect them under `constraints/`.

**Comment by bruth** [comment]
Right now, multi-column variants are represented using multiple lines with the name as the *grouper*. Of course this requires name to be provided.

`ref_table` and `ref_field` in the definition files are not the same thing as foreign keys. Obviously there is a large overlap, but I kept them because of this [edge case](https://github.com/chop-dbhi/data-models/blob/master/omop/v5/definitions/cohort.csv#L5).. a `subject_id` could reference records in multiple tables, but there is not foreign key constraint applied.

We can move the `references.csv` under constraints. I kept them separate simply because the file structure is different. That being said, the code that produces the various views relies on the file structure to determine the contents, not the directory structure.

**Comment by murphyke** [comment]
Sounds good.  What do you feel about the JSON sample in PEDSnet/pedsnetcdms#9 as an implicit spec?  I created that based on changes that Aaron suggested to the original JSON format that he created for pedsnetcdms.

**Comment by bruth** [comment]
Sure, that looks straightforward.

**Comment by bruth** [comment]
Implemented in 71e206d0b
