### ISSUE TITLE
Use content negotiation to determine output format

### ISSUE THREAD

**Issue by bruth** [chop-dbhi/data-models#25]
The order precedence is:

- `Accept` header e.g. `Accept: application/json`
- Extension on URL, e.g.  `/models/pcornet/v1.html`

**Comment by aaron0browne** [comment]
It would make a lot of sense to me if rather than having a separate path for json with `api/` prepended, all the file types existed at the same endpoints and could be requested either by `Accept` header, file extension, or url query parameter. I imagine this precedence:

- Missing all parameters returns `html`.
- `Accept` header precedes file extension precedes url query parameter.
- `md` and `markdown` are synonyms.

This would also remove the need for the current index page and likely promote the [models page](http://data-models.origins.link/models) to the index position.

**Comment by bruth** [comment]
Yes this ticket was intended to converge the endpoints, at the least the common ones. The API itself will be eventually be self-describing (via the `Link` header) and have more granular and composite resources (such as #18).

**Comment by bruth** [comment]
I left off support for a file extension since I do not see it adding any value compared to the `format` URL parameter.
