### ISSUE TITLE
PEDSnet v2.1

### ISSUE THREAD

**Issue by aaron0browne** [chop-dbhi/data-models#85]
@burrowse is ready work on PEDSnet CDM v2.1

@bruth how should we add this version without losing access to v2.0 in the data-models-service? (Related to chop-dbhi/data-models-service#7).

**Comment by bruth** [comment]
The approach is implemented in https://github.com/PEDSnet/pedsnet-origins/pull/26 for the ETL conventions service. For the data models service, it will require checking out the repo to the appropriate commit, building the graph, and then serving it up. A cache from commit &rarr; model can be added since the data does not change. An index from version to commit will be maintained as well to resolve which commit to serve up.

**Comment by bruth** [comment]
@burrowse Added v2.1 in #98
